name: Reviewdog
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.13"
      - name: Install Dependencies
        run: |
          cd src
          npm install
      - name: Launch Eslint inspection
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          workdir: "./src"
          eslint_flags: "resources/js"